apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-linode
spec:
  storageClassName: linode-block-storage-retain-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
